services:
  dsb-frontend:
    container_name: dsb-frontend
    image: ghcr.io/prtmphlp/dsb-frontend:latest
    restart: unless-stopped
    #build: ../frontend/
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - 3003:3000

  dsb-scraper:
    build: .
    container_name: dsb-scraper
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      - DSB_USERNAME=${DSB_USERNAME}
      - DSB_PASSWORD=${DSB_PASSWORD}
    volumes:
      - ./json:/app/json

volumes:
  json:
